// CipherX — Stealth Addresses (Phase 3)
//
// One-time addresses per transaction — Monero-style.
//
// Each CipherX address has two public keys:
//   B_spend  — controls spending
//   B_view   — controls scanning (can be shared read-only)
//
// Per transaction, sender generates a random r and:
//   1. R = r*G                      (included in tx — public)
//   2. s = H(r * B_view)            (shared secret)
//   3. P = H(s)*G + B_spend         (one-time output pubkey)
//
// Recipient scans every tx:
//   1. s = H(a * R)  where a = private view key
//   2. P' = H(s)*G + B_spend
//   3. If P' == P → this output is mine!
//   4. Spend key: x = H(s) + b  where b = private spend key
//
// Observer sees only R and P — both look like random points.
// Cannot link P to the recipient's public address.

use curve25519_dalek::{
    ristretto::{RistrettoPoint, CompressedRistretto},
    scalar::Scalar,
    constants::RISTRETTO_BASEPOINT_POINT,
};
use sha3::{Sha3_512, Sha3_256, Digest};
use rand::rngs::OsRng;
use rand_core::RngCore;
use zeroize::Zeroize;

use crate::crypto::keys::{StealthAddress, PrivateKey, PublicKey, ViewKey};

type Point = RistrettoPoint;
const G: Point = RISTRETTO_BASEPOINT_POINT;

// ─── Hash helpers ─────────────────────────────────────────────────────────────

/// H_s(P) → Scalar used in stealth derivation
fn hash_shared_secret(point: &Point) -> Scalar {
    let mut h = Sha3_512::new();
    h.update(b"CipherX_stealth_hs");
    h.update(point.compress().as_bytes());
    let hash = h.finalize();
    let mut bytes = [0u8; 64];
    bytes.copy_from_slice(&hash);
    Scalar::from_bytes_mod_order_wide(&bytes)
}

/// H_n(s, i) → Scalar for output index i within same tx
/// Allows multiple outputs to same recipient in one tx
fn hash_output_index(shared_secret: &Scalar, output_index: u32) -> Scalar {
    let mut h = Sha3_512::new();
    h.update(b"CipherX_stealth_hn");
    h.update(shared_secret.as_bytes());
    h.update(&output_index.to_le_bytes());
    let hash = h.finalize();
    let mut bytes = [0u8; 64];
    bytes.copy_from_slice(&hash);
    Scalar::from_bytes_mod_order_wide(&bytes)
}

fn point_from_bytes(bytes: &[u8; 32]) -> Option<Point> {
    CompressedRistretto(*bytes).decompress()
}

fn point_to_bytes(p: &Point) -> [u8; 32] {
    *p.compress().as_bytes()
}

fn scalar_from_bytes(bytes: &[u8; 32]) -> Option<Scalar> {
    let opt = Scalar::from_canonical_bytes(*bytes);
    if opt.is_some().into() { Some(opt.unwrap()) } else { None }
}

// ─── Sender side ──────────────────────────────────────────────────────────────

/// Generated by sender for each transaction output
pub struct StealthOutputKeys {
    /// R = r*G — included in transaction (public)
    pub tx_pubkey: [u8; 32],
    /// P — one-time output public key
    pub one_time_pubkey: [u8; 32],
    /// Shared secret scalar (kept private by sender, used to encrypt amount)
    pub shared_secret: Scalar,
}

/// Generate a one-time stealth output for a recipient.
///
/// # Arguments
/// * `recipient`    — recipient's stealth address (B_spend, B_view)
/// * `output_index` — output index within the transaction (for multiple outputs)
///
/// # Returns
/// `StealthOutputKeys` containing R (public) and P (one-time pubkey)
pub fn generate_output(
    recipient: &StealthAddress,
    output_index: u32,
) -> Result<StealthOutputKeys, String> {
    // Decompress recipient keys
    let b_spend = point_from_bytes(&recipient.public_spend.0)
        .ok_or("Invalid recipient spend key")?;
    let b_view = point_from_bytes(&recipient.public_view.0)
        .ok_or("Invalid recipient view key")?;

    // Random transaction key r
    let r = { let mut bytes = [0u8; 64]; OsRng.fill_bytes(&mut bytes); Scalar::from_bytes_mod_order_wide(&bytes) };

    // R = r*G (public, included in tx)
    let r_point = r * G;

    // Shared secret: s = H_s(r * B_view)
    let shared_point = r * b_view;
    let mut s = hash_shared_secret(&shared_point);

    // For output i: derive indexed secret
    let s_i = hash_output_index(&s, output_index);

    // One-time output pubkey: P = H_n(s,i)*G + B_spend
    let one_time_pk = s_i * G + b_spend;

    // Zeroize r after use
    let tx_pubkey = point_to_bytes(&r_point);
    let one_time_pubkey = point_to_bytes(&one_time_pk);
    let shared_secret = s_i;

    // Clear sensitive data
    s.zeroize();

    Ok(StealthOutputKeys {
        tx_pubkey,
        one_time_pubkey,
        shared_secret,
    })
}

// ─── Recipient side (scanning) ────────────────────────────────────────────────

/// Result of scanning an output
pub struct ScanResult {
    /// One-time private key to spend this output
    pub one_time_private_key: [u8; 32],
    /// Confirmed one-time public key (matches what's on chain)
    pub one_time_pubkey: [u8; 32],
}

/// Scan a transaction output to check if it belongs to us.
///
/// # Arguments
/// * `tx_pubkey`    — R from the transaction (r*G)
/// * `output_pubkey`— P from the transaction (one-time key)
/// * `output_index` — index of this output in the transaction
/// * `view_key`     — our private view key (a)
/// * `spend_pubkey` — our public spend key (B_spend)
/// * `spend_privkey`— our private spend key (b), if available (for spending)
///
/// # Returns
/// `Some(ScanResult)` if output belongs to us, `None` otherwise
pub fn scan_output(
    tx_pubkey: &[u8; 32],
    output_pubkey: &[u8; 32],
    output_index: u32,
    view_key: &ViewKey,
    spend_pubkey: &PublicKey,
) -> Option<[u8; 32]> {
    // Decompress R
    let r_point = point_from_bytes(tx_pubkey)?;

    // Decompress our spend pubkey
    let b_spend = point_from_bytes(&spend_pubkey.0)?;

    // Our private view key scalar
    let a = scalar_from_bytes(&view_key.0)?;

    // Shared secret: s = H_s(a * R)
    let shared_point = a * r_point;
    let s = hash_shared_secret(&shared_point);

    // Indexed secret for this output
    let s_i = hash_output_index(&s, output_index);

    // Expected one-time pubkey: P' = H_n(s,i)*G + B_spend
    let expected_pk = point_to_bytes(&(s_i * G + b_spend));

    // Check if it matches
    if expected_pk == *output_pubkey {
        // Return the one-time private key for spending:
        // x = H_n(s,i) + b  (where b = private spend key)
        // Caller adds their private spend key to get full x
        // We return s_i — caller adds their spend private key
        Some(s_i.to_bytes())
    } else {
        None
    }
}

/// Derive the full one-time private key for spending
/// x = s_i + b  (where b = private spend key scalar)
pub fn derive_spend_key(
    s_i_bytes: &[u8; 32],
    private_spend_key: &PrivateKey,
) -> Option<[u8; 32]> {
    let s_i = scalar_from_bytes(s_i_bytes)?;
    let b = scalar_from_bytes(&private_spend_key.0)?;
    let x = s_i + b;
    Some(x.to_bytes())
}

// ─── Key generation ───────────────────────────────────────────────────────────

/// Generate a full CipherX keypair
pub struct KeyPair {
    pub private_spend: PrivateKey,
    pub private_view: ViewKey,
    pub public_spend: PublicKey,
    pub public_view: PublicKey,
    pub address: StealthAddress,
}

pub fn generate_keypair() -> KeyPair {
    // Generate spend keypair
    let spend_scalar = { let mut bytes = [0u8; 64]; OsRng.fill_bytes(&mut bytes); Scalar::from_bytes_mod_order_wide(&bytes) };
    let spend_point = spend_scalar * G;
    let private_spend = PrivateKey(spend_scalar.to_bytes());
    let public_spend = PublicKey(point_to_bytes(&spend_point));

    // Generate view keypair (deterministically from spend key for convenience)
    // In production: view_key = H(spend_key) — allows separate view-only wallet
    let mut h = Sha3_256::new();
    h.update(b"CipherX_view_key");
    h.update(spend_scalar.as_bytes());
    let view_hash = h.finalize();
    let mut view_bytes = [0u8; 32];
    view_bytes.copy_from_slice(&view_hash);

    // Convert to valid scalar
    let view_scalar_opt = Scalar::from_canonical_bytes(view_bytes);
    let view_scalar = if view_scalar_opt.is_some().into() {
        view_scalar_opt.unwrap()
    } else {
        { let mut bytes = [0u8; 64]; OsRng.fill_bytes(&mut bytes); Scalar::from_bytes_mod_order_wide(&bytes) }
    };

    let view_point = view_scalar * G;
    let private_view = ViewKey(view_scalar.to_bytes());
    let public_view = PublicKey(point_to_bytes(&view_point));

    let address = StealthAddress {
        public_spend: public_spend.clone(),
        public_view: public_view.clone(),
    };

    KeyPair {
        private_spend,
        private_view,
        public_spend,
        public_view,
        address,
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_output_and_scan() {
        // Generate recipient keypair
        let recipient = generate_keypair();

        // Sender generates stealth output
        let output_keys = generate_output(&recipient.address, 0).unwrap();

        // Recipient scans the output
        let scan_result = scan_output(
            &output_keys.tx_pubkey,
            &output_keys.one_time_pubkey,
            0,
            &recipient.private_view,
            &recipient.public_spend,
        );

        assert!(scan_result.is_some(), "Recipient should detect their own output");
    }

    #[test]
    fn test_wrong_recipient_cannot_detect() {
        let recipient = generate_keypair();
        let wrong_recipient = generate_keypair();

        let output_keys = generate_output(&recipient.address, 0).unwrap();

        // Wrong recipient should NOT detect this output
        let scan_result = scan_output(
            &output_keys.tx_pubkey,
            &output_keys.one_time_pubkey,
            0,
            &wrong_recipient.private_view,
            &wrong_recipient.public_spend,
        );

        assert!(scan_result.is_none(), "Wrong recipient must not detect output");
    }

    #[test]
    fn test_multiple_outputs_same_tx() {
        let recipient = generate_keypair();

        // Two outputs to same recipient in same tx (different output index)
        let out0 = generate_output(&recipient.address, 0).unwrap();
        let out1 = generate_output(&recipient.address, 1).unwrap();

        // Both should be detectable
        assert!(scan_output(&out0.tx_pubkey, &out0.one_time_pubkey, 0,
            &recipient.private_view, &recipient.public_spend).is_some());
        assert!(scan_output(&out1.tx_pubkey, &out1.one_time_pubkey, 1,
            &recipient.private_view, &recipient.public_spend).is_some());

        // Output 0 with index 1 should NOT match
        assert!(scan_output(&out0.tx_pubkey, &out0.one_time_pubkey, 1,
            &recipient.private_view, &recipient.public_spend).is_none());
    }

    #[test]
    fn test_one_time_pubkeys_are_unique() {
        let r1 = generate_keypair();
        let r2 = generate_keypair();

        let o1 = generate_output(&r1.address, 0).unwrap();
        let o2 = generate_output(&r2.address, 0).unwrap();

        // Different recipients → different one-time pubkeys (unlinkable)
        assert_ne!(o1.one_time_pubkey, o2.one_time_pubkey);
    }

    #[test]
    fn test_address_encoding() {
        let kp = generate_keypair();
        let addr = kp.address.to_string();
        assert!(addr.starts_with("CX1"));
        println!("CipherX address: {}", addr);
    }

    #[test]
    fn test_spend_key_derivation() {
        let recipient = generate_keypair();
        let output_keys = generate_output(&recipient.address, 0).unwrap();

        let s_i = scan_output(
            &output_keys.tx_pubkey,
            &output_keys.one_time_pubkey,
            0,
            &recipient.private_view,
            &recipient.public_spend,
        ).unwrap();

        // Derive full spend key
        let spend_key = derive_spend_key(&s_i, &recipient.private_spend);
        assert!(spend_key.is_some());

        // Verify: x*G should equal the one-time pubkey
        let x = Scalar::from_canonical_bytes(spend_key.unwrap());
        if x.is_some().into() {
            let derived_pk = point_to_bytes(&(x.unwrap() * G));
            assert_eq!(derived_pk, output_keys.one_time_pubkey,
                "Derived spend key must reproduce the one-time pubkey");
        }
    }
}
